version: "3"
services:

  meshBackup:
    image: docker.apa-it.at/gentics/mesh:1.6.13
    container_name: mesh-backup
    environment:
      - MESH_ELASTICSEARCH_URL=null
      - MESH_AUTH_KEYSTORE_PASS=changeme
      - MESH_CLUSTER_ENABLED=true
      - MESH_CLUSTER_NAME=mesh-docker-cluster
      - MESH_CLUSTER_VERTX_PORT=4848
      - MESH_NODE_NAME=backup-node
    ports:
      - '8088:8080'
    volumes:
      - ./backup:/backup
      - mesh-keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
