version: "3"
services:

  mesh:
    image: gentics/mesh:1.4.3
    container_name: mesh-server
    environment:
      - MESH_AUTH_KEYSTORE_PASS=changeme
      - MESH_INITIAL_ADMIN_PASSWORD=admin
      - MESH_INITIAL_ADMIN_PASSWORD_FORCE_RESET=false
    stop_grace_period: 5m
    ports:
      - '8080:8080'
    volumes:
      - mesh-data:/graphdb
      - mesh-uploads:/uploads
      - mesh-keystore:/keystore
      - ./logback.xml:/config/logback.xml
      - ./log:/mesh/log
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

volumes:
  mesh-keystore:
    driver: local
  mesh-data:
    driver: local
  mesh-uploads:
    driver: local
