version: "3"
services:

  mesh:
    image: gentics/mesh:0.27.2
    container_name: mesh-server
    environment:
      - MESH_ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESH_ELASTICSEARCH_START_EMBEDDED=false
      - MESH_AUTH_KEYSTORE_PASS=changeme
    stop_grace_period: 5m
    ports:
      - '8081:8080'
    volumes:
      - mesh-data:/graphdb
      - mesh-uploads:/uploads
      - mesh-keystore:/keystore
      - ./mesh-config/mesh.yml:/config/mesh.yml
      - ./mesh-config/mapperscript.js:/config/mapperscript.js
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: mesh-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    stop_grace_period: 5m
    ports:
      - '127.0.0.1:9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - '127.0.0.1:8082:8080'
    command: [
        "-b",
        "0.0.0.0",
        "-Dkeycloak.migration.usersExportStrategy=SAME_FILE",
        "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
        "-Dkeycloak.import=/opt/jboss/keycloak/realm.json" 
      ]
    volumes:
      - ./keycloak/realm.json:/opt/jboss/keycloak/realm.json

volumes:
  esdata:
    driver: local
  mesh-keystore:
    driver: local
  mesh-data:
    driver: local
  mesh-uploads:
    driver: local
