version: "3"
services:

  meshA:
    image: gentics/mesh:0.29.10
    container_name: mesh-server-a
    environment:
      - MESH_ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESH_ELASTICSEARCH_START_EMBEDDED=false
      - MESH_AUTH_KEYSTORE_PASS=changeme
      - MESH_CLUSTER_ENABLED=true
      - MESH_CLUSTER_NAME=mesh-docker-cluster
      - MESH_NODE_NAME=nodeA
      - MESH_CLUSTER_VERTX_PORT=4848
      - MESH_CLUSTER_INIT=true
    ports:
      - '8081:8080'
    volumes:
      - meshdata-a:/graphdb
      - mesh-uploads:/uploads
      - mesh-keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

  meshB:
    image: gentics/mesh:0.29.10
    container_name: mesh-server-b
    environment:
      - MESH_ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESH_ELASTICSEARCH_START_EMBEDDED=false
      - MESH_AUTH_KEYSTORE_PASS=changeme
      - MESH_CLUSTER_ENABLED=true
      - MESH_CLUSTER_NAME=mesh-docker-cluster
      - MESH_CLUSTER_VERTX_PORT=4848
      - MESH_NODE_NAME=nodeB
    ports:
      - '8082:8080'
    volumes:
      - meshdata-b:/graphdb
      - mesh-uploads:/uploads
      - mesh-keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

  meshC:
    image: gentics/mesh:0.29.10
    container_name: mesh-server-c
    environment:
      - MESH_ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESH_ELASTICSEARCH_START_EMBEDDED=false
      - MESH_AUTH_KEYSTORE_PASS=changeme
      - MESH_CLUSTER_ENABLED=true
      - MESH_CLUSTER_NAME=mesh-docker-cluster
      - MESH_CLUSTER_VERTX_PORT=4848
      - MESH_NODE_NAME=nodeC
    ports:
      - '8083:8080'
    volumes:
      - meshdata-c:/graphdb
      - mesh-uploads:/uploads
      - mesh-keystore:/keystore
    ulimits:
      nofile:
        soft: 20000
        hard: 40000


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    container_name: mesh-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '127.0.0.1:9200:9200'
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  lb:
    image: nginx
    container_name: loadbalancer
    volumes:
      - ./nginx/lb.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8080:80'
    depends_on:
      - meshA
      - meshB
      - meshC

volumes:
  mesh-keystore:
    driver: local
  esdata:
    driver: local
  mesh-uploads:
    driver: local
  meshdata-a:
    driver: local
  meshdata-b:
    driver: local 
  meshdata-c:
    driver: local
